apiVersion: v1
kind: Service
metadata:
  name: python-gunicorn-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: python-gunicorn-app
  ports:
    - port: 80
      targetPort: 80
